- lib/generators/fx/function/function_generator.rb
- lib/generators/fx/function/templates/db/migrate/create_function.erb
- lib/generators/fx/function/templates/db/migrate/update_function.erb
- lib/generators/fx/trigger/templates/db/migrate/create_trigger.erb
- lib/generators/fx/trigger/templates/db/migrate/update_trigger.erb
- lib/generators/fx/trigger/trigger_generator.rb
Rails 5 introduced versioned migrations to cope with breaking changes in
the migrations API. To remedy those breakages, versioned migrations were
introduced.
The new migration syntax is only generated on Rails 5.0 and above.
> Generate migrations warning free on Rails 5

- lib/fx/adapters/postgres/functions.rb
- lib/fx/adapters/postgres/triggers.rb
Our previous strategy of relying on postgres to give us the
triggers/functions in the correct order was incorrect.
Those tables have no specific ordering so the results can come back in
any order.
Ordering by 'oid' is the simplest way to order everything by insertion
order. Dropping a view that depends on a child view also requires
dropping that child view, so ordering in this manner should be
sufficient.
> Order triggers and functions by Postgres oid

- .travis.yml
- lib/fx/adapters/postgres/functions.rb
- lib/fx/adapters/postgres/triggers.rb
- spec/acceptance/user_manages_functions_spec.rb
- spec/acceptance/user_manages_triggers_spec.rb
- spec/features/functions/migrations_spec.rb
- spec/features/functions/revert_spec.rb
- spec/features/triggers/migrations_spec.rb
- spec/features/triggers/revert_spec.rb
- spec/fx/adapters/postgres_spec.rb
- spec/fx/definition_spec.rb
- spec/fx/schema_dumper/function_spec.rb
- spec/fx/schema_dumper/trigger_spec.rb
Which currently is 2.1.*, 2.2.*, 2.3.*
- Test against all supported rubies on Travis.
- Allow 2.1.* to fail against Rails 5.0 since Rails requires 2.2.* or
above.
- Remove usage of squiggly-heredocs(`<<~`).
Since we want to support all supported version of Ruby, we have to use
features that are available between all of them. Squiggly-heredocs are
only available in 2.3.* and above.
- Simplify tests for:
- `Fx::Adapters::Postgres::Functions#functions`
- `Fx::Adapters::Postgres::Triggers#triggers`
> Support all supported ruby versions

- Appraisals
- bin/setup
- gemfiles/rails40.gemfile.lock
- gemfiles/rails41.gemfile.lock
- gemfiles/rails42.gemfile.lock
- gemfiles/rails50.gemfile.lock
- gemfiles/rails_edge.gemfile
- gemfiles/rails_edge.gemfile.lock
- spec/acceptance_helper.rb
- spec/dummy/Rakefile
- Some developers were seeing test suite failures under Rails 5 because
`rake db:environment:set` needed to be run. This task doesn't exist in
earlier versions of Rails, so we created a dummy task in the dummy app
so we could call it nonetheless.
- Edge rails appraisal doesn't need edge RSpec.
- Update appraisals.
> Fix test suite issues

- lib/fx/statements/function.rb
- lib/fx/statements/trigger.rb
If the whitespace isn't stripped, the whitespace finds its way into the actual function definitions. Successive runs of `schema:load` and `schema:dump` will add 6 spaces of indentation to the function definition (each time). The indentation keeps growing and growing, which results in a lot of churn in schema.rb and unnecessary merge conflicts between disparate source control branches.
> Strip shared leading whitespace from sql_definitions

- README.md
This is used to specify which table the trigger will be applied.  Also if this is not there, the generator command errors
> Adding table_name to rails generator readme

- README.md
The README describes how to create a trigger and a function, but when
building a trigger that relies on a function, the function needs to
exist first. Following the suggestions in order will create a migration
that doesn't work because of an uncreated function dependency.
> Reverse function/trigger order in README

- .travis.yml
- lib/fx/adapters/postgres.rb
- spec/acceptance/user_manages_functions_spec.rb
- spec/fx/adapters/postgres_spec.rb
copy of #26 just a different sourcebranch
With postgres version above 10 you don't need to send the arguments for dropping function.
In our project we have created functions like car_active, it takes a date as an argument. When we needed to update it we would use the trick https://github.com/teoljungberg/fx/issues/12#issuecomment-390002371.
Since version 10 it is possible to drop functions without passing the arguments so I went ahead and implemented it today. 
I'm not 100% sure know you will take this. I found one of your old Pull request. I dont know why you closed it https://github.com/teoljungberg/fx/pull/8. 
I have seen there has been done some work in the past tring to implemnet both function with arguments and multiple functions same name with different agruments. This solved the …
> Support functions with parameters

- .travis.yml
This PR removes Rails 4.0 and 4.1 from Travis' matrix for allowed
failures, as they have been removed in #31.
> Remove 4.0 and 4.1 from the failure matrix

- README.md
This PR adds a new "Contributing" section to the `README` which
links to the existing`CONTRIBUTING` file, so that it can be easily
accessible via `README`.
> Add "Contributing" section in README

- lib/fx/adapters/postgres.rb
First off, just want to say thanks for creating this gem -- I'm excited to use it in my project!
I might be strange, but on my dev machine I don't have a postgres database for my user (i.e., if I just type `psql` at the console, I get an error "psql: FATAL:  database "ryan" does not exist"). I have to specify the dbname. Because of this, I get an error when the code attempt to check the postgres server version. 
I wasn't sure what a good way to build a test for this would be without impacting the dev machine (I don't want to drop anyone's DB!), so I did not include an update to any spec file. However, before the change, specs fail for me. With the change, I'm green.
Looking forward to any comments/feedback on this change. Thanks again and commit body below:
------
Using the Rails db …
> Use db connection provided by Rails

- lib/generators/fx/function/USAGE
- lib/generators/fx/function/function_generator.rb
- lib/generators/fx/trigger/USAGE
- lib/generators/fx/trigger/trigger_generator.rb
- spec/generators/fx/function/function_generator_spec.rb
- spec/generators/fx/trigger/trigger_generator_spec.rb
Based on Rails [Model generator](https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/rails/generators/active_record/model/model_generator.rb#L12)
I couldn't get the test suite to run locally
My use case is mostly that I'm just starting to use fx in my project and most of the time I want to generator a v1 before I use fx to change it, and I keep having to delete the migrations generated
> Support --no-migration generator flag

- lib/fx/adapters/postgres/functions.rb
- spec/fx/schema_dumper/function_spec.rb
Calling `pg_get_functiondef(some_oid)` on aggregates fails. Assuming
this gem is not meant to support aggregate functions, aggregate functions
are now excluded via omitting them from the query that pulls function
definitions from PG. This is achieved by checking for the function's
presence in table `pg_aggregate`.
`pg_aggregate` is present in all officially supported PG versions ( >= 9.4 ).
> Does not include aggregates when dumping schema (#34)

- lib/generators/fx/function/function_generator.rb
- lib/generators/fx/trigger/trigger_generator.rb
- spec/generators/fx/trigger/trigger_generator_spec.rb
- Fix impl and tests in https://github.com/teoljungberg/fx/pull/60
I figured out how to run the tests (on reflection, it's not hard, so don't know what my issue was before, maybe just appraisal
basically I (on Ruby 2.6.2)
```sh
export BUNDLE_GEMFILE=gemfiles/rails60.gemfile
gem install bundler --conservative
bundle check || bundle install
bundle exec rake dummy:db:drop
bundle exec rake dummy:db:create
bundle exec rake
```
> Fix: Support --no-migration generator flag

- lib/fx/function.rb
- spec/fx/function_spec.rb
- spec/fx/schema_dumper/function_spec.rb
This is an alternative to https://github.com/teoljungberg/fx/pull/51 that fixes the same problem, but in a way that is more obviously-correct.
If a Postgres function contains backslashes (common in regexes e.g. \s
or \1), then we write those backslashes into a heredoc in schema.rb
without escaping them. So if you load your database from schema.rb, ruby
interprets the backslashes instead of preserving them for Postgres.
Rather than trying to escape every possible thing, this commit uses a
single-quote heredoc (<<-'SQL') which treats all characters literally.
> Preserve backslashes when dumping the schema

- .travis.yml
- Appraisals
- gemfiles/rails42.gemfile
- lib/fx/statements/function.rb
- lib/fx/statements/trigger.rb
The biggest change in Ruby 3 is [how keyword parameters are distinct
from positional parameters][1]. If we want to support 3 and pre-3, we
need to take a single hash as a positional parameter (`option = {}`). If
we use the `**option` syntax then things fail on the Ruby 3/Rails 6
combo because of how Rails calls our methods.
I also updated the Travis & Appraisal files. There is no need to support
Rails pre-6 on Ruby 3, since [Rails itself has no plans to support
it][2].
[1]: https://rubyreferences.github.io/rubychanges/3.0.html#keyword-arguments-are-now-fully-separated-from-positional-arguments
[2]: https://github.com/rails/rails/issues/40938
> Support Ruby 3

- .github/workflows/ci.yml
- fx.gemspec
Rails < 6.1 (and 6.0 specifically) hit EOL on 1/6/2023.
> Require Rails >= 6.1

- .github/workflows/ci.yml
- lib/fx/adapters/postgres/functions.rb
- lib/fx/adapters/postgres/triggers.rb
- spec/dummy/config/application.rb
https://github.com/rails/rails/releases/tag/v7.1.0
Changes:
- Appease standard by using `...`. I will investigate why it is needed
for these 2 cases in a separate PR.
> Add Rails 7.1 to test matrix

- lib/fx.rb
- lib/fx/configuration.rb
Rather than having `lib/fx/configuration.rb` re-open the `Fx` module, it
makes more sense to have the methods for `Fx.configuration`,
`Fx.configuration=`, and `Fx.configure` live inside `lib/fx.rb`.
> Move configuration methods to `Fx`

- spec/generators/fx/function/function_generator_spec.rb
- spec/generators/fx/trigger/trigger_generator_spec.rb
> DEPRECATION WARNING: The `exist` matcher overrides one built-in by
> RSpec; use `expect(Pathname.new(path)).to exist` instead
> Fix deprecation warnings

- .github/workflows/ci.yml
- spec/fx/schema_dumper_spec.rb
https://github.com/rails/rails/releases/tag/v7.2.0
Changes:
- Send the connection's pool to `ActiveRecord::SchemaDumper.dump` for
Rails 7.2 and above.
> Add Rails 7.2 to test matrix

- lib/fx.rb
- spec/fx/configuration_spec.rb
- spec/fx_spec.rb
- Add explicit return value of `Fx.load`. Returning true over
`ActiveRecord::SchemaDumper` feels more expected.
- Test Fx's configuration per file.
> Refactor configuration tests

- .github/workflows/ci.yml
- fx.gemspec
- spec/dummy/config/application.rb
Changes:
- Drop support for Rails 6.2 to keep with the end of life policy.
> Bump Rails support to Rails 8

- .github/workflows/ci.yml
- fx.gemspec
We are dropping support for EOL'd Ruby and Rails versions, but keeping
those that still receive security updates due to that not causing extra
maintenance.
Changes:
- Require Ruby >= 3.1
- Drop EOL Ruby version (3.0)
- Drop EOL Rails version (7.0)
- Relax Rails 8's version requirement
> Update supported Ruby and Rails versions

- .github/workflows/ci.yml
- CHANGELOG.md
- fx.gemspec
> Bump minimum requirement to Ruby 3.2

- lib/fx/adapters/postgres/functions.rb
- lib/fx/adapters/postgres/triggers.rb
- spec/fx/adapters/postgres/functions_spec.rb
- spec/fx/adapters/postgres/triggers_spec.rb
Updates the function and trigger queries for PostgreSQL to only return objects from the current schema search path.
This is based on how Rails limits dumping objects like enums (rails/rails#47791).
Resolves #164.
> Scope functions and triggers to schema search path
